INSERT INTO categories (id,name,url) VALUES
 (1,'Bandas elásticas','bandas-elasticas'),
 (2,'Aluminio','aluminio'),
 (3,'Blondas de papel','blondas-de-papel'),
 (4,'Bobinas','bobinas'),
 (5,'Bolsas','bolsas'),
 (6,'Bombonera','bombonera'),
 (7,'Cajas','cajas'),
 (8,'Carteles','carteles'),
 (9,'Cartón corrugado','carton-corrugado'),
 (10,'Cintas','cintas'),
 (11,'Cubiertos','cubiertos'),
 (12,'Ensaladeras','ensaladeras'),
 (13,'Etiquetas','etiquetas'),
 (14,'Film strech','film-strech'),
 (15,'Fundas','fundas'),
 (16,'Guantes','guantes'),
 (17,'Hilos y cintas','hilos-y-cintas'),
 (18,'Láminas','laminas'),
 (19,'Moldes de papel','moldes-de-papel'),
 (20,'Moños','monos'),
 (21,'Papeles','papeles'),
 (22,'Pirotines','pirotines'),
 (23,'Platos','platos'),
 (24,'Portapanchos','portapanchos'),
 (25,'Potes','potes'),
 (26,'Precintos','precintos'),
 (27,'Resmas','resmas'),
 (28,'Rollos','rollos'),
 (29,'Servilletas','servilletas'),
 (30,'Sobres','sobres'),
 (31,'Sorbetes','sorbetes'),
 (32,'Talonarios','talonarios'),
 (33,'Tapas','tapas'),
 (34,'Torteras plásticas','torteras-plasticas'),
 (35,'Trípodes','tripodes'),
 (36,'Vasos','vasos');
